# Site settings
title: Ellis Island
email: EllisIslandRock@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Ellis Island: Rock that'll get you moving!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://ellisislandrock.com" # the base hostname & protocol for your site
twitter_username: EllisIslandRock

# Build settings
markdown: kramdown
