# Site settings
title: Ellis Island
email: band@ellisislandrock.com
description: > # this means to ignore newlines until "baseurl:"
  Ellis Island: Rock that'll get you moving!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://ellisislandrock.com" # the base hostname & protocol for your site
twitter_username: EllisIslandRock
facebook_username: EllisIslandRock
instagram_username: ellisislandband
youtube_username: Ellis Island
youtube_link: @ellisislandfairfieldct

# Build settings
markdown: kramdown
