# Site settings
title: Ellis Island
email: EllisIslandRock@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Ellis Island: Connecticut's Funnest Bar Band!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://ellisisland.com" # the base hostname & protocol for your site
# twitter_username: jmenard42

# Build settings
markdown: kramdown
